[package]
name        = "dev.peios.atrium-debuginfo"
description = "Atrium runtime debugging symbols"

[dependencies]
"dev.peios.atrium-core" = "{{version}}"

[files]
"@source:LICENSE"       = "usr/share/licenses/dev.peios.atrium-debuginfo/LICENSE"
":usr/lib/debug/**"     = "usr/lib/debug"
