[package]
name         = "dev.peios.atrium-app-registry"
architecture = "noarch"
description  = "Atrium application for registry configuration and documentation"

[dependencies]
"dev.peios.atrium-core" = "= {{release}}"
"dev.peios.peiosutils"                = "*"

[files]
"@source:LICENSE"                            = "usr/share/licenses/dev.peios.atrium-app-registry/LICENSE"
":usr/share/atrium/apps/org.peios.registry/**" = "usr/share/atrium/apps/org.peios.registry"
